[build]
  publish = "dist"
  command = "npm run build"
  environment = { NODE_VERSION = "24", NODE_ENV = "production" }

[template.environment]
  ACKEE_MONGODB = "ACKEE_MONGODB"
  ACKEE_USERNAME = "ACKEE_USERNAME"
  ACKEE_PASSWORD = "ACKEE_PASSWORD"
  ACKEE_ALLOW_ORIGIN = "ACKEE_ALLOW_ORIGIN"
  ACKEE_AUTO_ORIGIN = "ACKEE_AUTO_ORIGIN"
