export const EVENTS_TYPE_TOTAL_CHART = 'TOTAL_CHART'
export const EVENTS_TYPE_AVERAGE_CHART = 'AVERAGE_CHART'
export const EVENTS_TYPE_TOTAL_LIST = 'TOTAL_LIST'
export const EVENTS_TYPE_AVERAGE_LIST = 'AVERAGE_LIST'
